In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

In [2]:
custumer=pd.read_csv('C:\\Users\\sadra\\Desktop\\Notebook\\Churn_Modelling.csv')

In [4]:
custumer.head(6)

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   
5          6    15574012       Chu          645     Spain    Male   44   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   
5       8  113755.78              2          1               0   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0  
5        149756.71       1

In [5]:
x=custumer.iloc[:,3:-1]
y=custumer.iloc[:,-1]

In [6]:
x

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  EstimatedSalary  
0             1               1        101348.88  
1             0               1        112542.58  
2             1               0        113931.57  
3             0               0         93826.63  
4             1               1         79084.10  
...         ...             ...              ...  
9995          1               0         96270.64  
9996          1               1        101699.77  
9997          0               1         42085.58  
9998          1               0         92888.52  
9999          1               0         38190.78  

[10000 rows x 10 columns]

In [7]:
y


0       1
1       0
2       1
3       0
4       0
       ..
9995    0
9996    0
9997    1
9998    1
9999    0
Name: Exited, Length: 10000, dtype: int64

In [8]:
x=x.values
y=y.values

In [9]:
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [10]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
le=LabelEncoder()

In [13]:
x[:,2]=le.fit_transform(x[:,2])

In [14]:
x

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [15]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')


In [17]:
ct.fit_transform(x)

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [18]:
x=ct.transform(x)

In [19]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [20]:
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [23]:
y_test

array([0, 1, 0, ..., 0, 0, 0], dtype=int64)

In [24]:
x_test

array([[0.0, 1.0, 0.0, ..., 1, 1, 192852.67],
       [1.0, 0.0, 0.0, ..., 1, 0, 128702.1],
       [0.0, 0.0, 1.0, ..., 1, 1, 75732.25],
       ...,
       [0.0, 0.0, 1.0, ..., 1, 0, 141533.19],
       [0.0, 1.0, 0.0, ..., 1, 1, 11276.48],
       [0.0, 1.0, 0.0, ..., 1, 0, 192950.6]], dtype=object)

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
sc=StandardScaler()

In [27]:
x_train

array([[0.0, 0.0, 1.0, ..., 1, 0, 163830.64],
       [0.0, 1.0, 0.0, ..., 1, 1, 57098.0],
       [1.0, 0.0, 0.0, ..., 1, 0, 185630.76],
       ...,
       [1.0, 0.0, 0.0, ..., 1, 0, 181429.87],
       [0.0, 0.0, 1.0, ..., 1, 1, 148750.16],
       [0.0, 1.0, 0.0, ..., 1, 0, 118855.26]], dtype=object)

In [28]:
sc.fit_transform(x_train)

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

In [29]:
x_train=sc.fit_transform(x_train)

In [30]:
x_test=sc.fit_transform(x_test)

In [31]:
ann=tf.keras.models.Sequential()

In [32]:
ann.add(tf.keras.layers.Dense(units=35,activation='relu'))
ann.add(tf.keras.layers.Dense(units=35,activation='relu'))
ann.add(tf.keras.layers.Dense(units=64,activation='relu'))
ann.add(tf.keras.layers.Dense(units=128,activation='relu'))

In [33]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [34]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [35]:
ann.fit(x_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 [==============================] - 3s 5ms/step - loss: 0.4409 - accuracy: 0.8114
Epoch 2/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3598 - accuracy: 0.8499
Epoch 3/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3464 - accuracy: 0.8566
Epoch 4/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3382 - accuracy: 0.8615
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3324 - accuracy: 0.8635
Epoch 6/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3279 - accuracy: 0.8649
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3229 - accuracy: 0.8676
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3201 - accuracy: 0.8685
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3170 - accuracy: 0.8691
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3127 - accura

250/250 [==============================] - 1s 4ms/step - loss: 0.1090 - accuracy: 0.9554
Epoch 82/100
250/250 [==============================] - 1s 5ms/step - loss: 0.1079 - accuracy: 0.9569
Epoch 83/100
250/250 [==============================] - 1s 4ms/step - loss: 0.0953 - accuracy: 0.9620
Epoch 84/100
250/250 [==============================] - 1s 4ms/step - loss: 0.0991 - accuracy: 0.9599
Epoch 85/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1043 - accuracy: 0.9565
Epoch 86/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1058 - accuracy: 0.9559
Epoch 87/100
250/250 [==============================] - 1s 4ms/step - loss: 0.0813 - accuracy: 0.9710
Epoch 88/100
250/250 [==============================] - 1s 4ms/step - loss: 0.0793 - accuracy: 0.9699
Epoch 89/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1033 - accuracy: 0.9592
Epoch 90/100
250/250 [==============================] - 1s 4ms/step - loss: 0.1031 - accuracy: 